package cmd

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var genCmd = &cobra.Command{
	Use:   "gen",
	Short: "Code generation commands",
	Long:  "Generate types from database schema",
}

var genTypesCmd = &cobra.Command{
	Use:   "types",
	Short: "Generate type definitions from database schema",
	Run: func(cmd *cobra.Command, args []string) {
		dbID, _ := cmd.Flags().GetString("db")
		lang, _ := cmd.Flags().GetString("lang")
		output, _ := cmd.Flags().GetString("output")

		if dbID == "" {
			fmt.Fprintln(os.Stderr, "Error: --db is required")
			os.Exit(1)
		}

		tables := getTableSchema(dbID)
		
		if len(tables) == 0 {
			fmt.Fprintln(os.Stderr, "No tables found in database")
			return
		}
		
		var code string
		switch lang {
		case "typescript":
			code = generateTypeScript(tables)
		case "python":
			code = generatePython(tables)
		case "go":
			code = generateGo(tables)
		default:
			fmt.Fprintln(os.Stderr, "Error: unsupported language. Use typescript, python, or go")
			os.Exit(1)
		}

		if output != "" {
			os.WriteFile(output, []byte(code), 0644)
			fmt.Printf("Types written to %s\n", output)
		} else {
			fmt.Println(code)
		}
	},
}

type Column struct {
	Name     string
	Type     string
	Nullable bool
}

type Table struct {
	Name    string
	Columns []Column
}

func getTableSchema(dbID string) []Table {
	introspectSQL := `SELECT table_name, column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema = 'public' ORDER BY table_name, ordinal_position`

	payload := map[string]string{"sql": introspectSQL}
	body, _ := json.Marshal(payload)
	
	resp, err := http.Post(apiURL+"/api/v1/databases/"+dbID+"/sql", "application/json", bytes.NewBuffer(body))
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		return []Table{}
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	
	tablesMap := make(map[string][]Column)
	if results, ok := result["results"].([]interface{}); ok {
		for _, row := range results {
			if r, ok := row.(map[string]interface{}); ok {
				tableName := fmt.Sprintf("%v", r["table_name"])
				col := Column{
					Name:     fmt.Sprintf("%v", r["column_name"]),
					Type:     fmt.Sprintf("%v", r["data_type"]),
					Nullable: fmt.Sprintf("%v", r["is_nullable"]) == "YES",
				}
				tablesMap[tableName] = append(tablesMap[tableName], col)
			}
		}
	}

	var tables []Table
	for name, cols := range tablesMap {
		tables = append(tables, Table{Name: name, Columns: cols})
	}
	return tables
}

func generateTypeScript(tables []Table) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by oc-db9\n\n")
	
	for _, table := range tables {
		sb.WriteString(fmt.Sprintf("export interface %s {\n", pascalCase(table.Name)))
		for _, col := range table.Columns {
			tsType := mapPostgresToTypeScript(col.Type)
			optional := ""
			if col.Nullable {
				optional = "?"
			}
			sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", col.Name, optional, tsType))
		}
		sb.WriteString("}\n\n")
	}
	
	return sb.String()
}

func generatePython(tables []Table) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by oc-db9\n\n")
	sb.WriteString("from dataclasses import dataclass\n")
	sb.WriteString("from typing import Optional\n\n")
	
	for _, table := range tables {
		sb.WriteString(fmt.Sprintf("@dataclass\n"))
		sb.WriteString(fmt.Sprintf("class %s:\n", pascalCase(table.Name)))
		for _, col := range table.Columns {
			pyType := mapPostgresToPython(col.Type, col.Nullable)
			sb.WriteString(fmt.Sprintf("    %s: %s\n", col.Name, pyType))
		}
		sb.WriteString("\n")
	}
	
	return sb.String()
}

func generateGo(tables []Table) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by oc-db9\n\n")
	sb.WriteString("package models\n\n")
	
	for _, table := range tables {
		sb.WriteString(fmt.Sprintf("type %s struct {\n", pascalCase(table.Name)))
		for _, col := range table.Columns {
			goType := mapPostgresToGo(col.Type)
			sb.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", pascalCase(col.Name), goType, col.Name))
		}
		sb.WriteString("}\n\n")
	}
	
	return sb.String()
}

func pascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(string(parts[i][0])) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func mapPostgresToTypeScript(pgType string) string {
	switch pgType {
	case "integer", "bigint", "smallint", "serial", "bigserial":
		return "number"
	case "text", "varchar", "character varying", "char", "uuid":
		return "string"
	case "boolean":
		return "boolean"
	case "timestamp with time zone", "timestamp", "timestamptz", "date", "time":
		return "Date"
	case "jsonb", "json":
		return "any"
	case "double precision", "real", "numeric":
		return "number"
	default:
		return "any"
	}
}

func mapPostgresToPython(pgType string, nullable bool) string {
	var pyType string
	switch pgType {
	case "integer", "bigint", "smallint", "serial", "bigserial":
		pyType = "int"
	case "text", "varchar", "character varying", "char", "uuid":
		pyType = "str"
	case "boolean":
		pyType = "bool"
	case "timestamp with time zone", "timestamp", "timestamptz", "date", "time":
		pyType = "datetime"
	case "jsonb", "json":
		pyType = "dict"
	case "double precision", "real", "numeric":
		pyType = "float"
	default:
		pyType = "Any"
	}
	
	if nullable {
		return "Optional[" + pyType + "]"
	}
	return pyType
}

func mapPostgresToGo(pgType string) string {
	switch pgType {
	case "integer", "serial":
		return "int32"
	case "bigint", "bigserial":
		return "int64"
	case "smallint":
		return "int16"
	case "text", "varchar", "character varying", "char", "uuid":
		return "string"
	case "boolean":
		return "bool"
	case "timestamp with time zone", "timestamp", "timestamptz":
		return "time.Time"
	case "date":
		return "time.Time"
	case "jsonb", "json":
		return "interface{}"
	case "double precision", "real", "numeric":
		return "float64"
	default:
		return "interface{}"
	}
}

func init() {
	rootCmd.AddCommand(genCmd)
	genCmd.AddCommand(genTypesCmd)

	genTypesCmd.Flags().String("db", "", "Database ID")
	genTypesCmd.Flags().String("lang", "typescript", "Language to generate (typescript, python, go)")
	genTypesCmd.Flags().String("output", "", "Output file path")
}
